temp = eval(input('Enter a temperature in Celsius: '))
f_temp = 9/5*temp+32
print('In Fahrenheit, that is' , f_temp)
if f_temp > 212:
    print('That temperature is above the boiling point.')
if f_temp < 32:
    print('That temperature is below the freezing point.') 
print('**********')
print('**********')
print('**********')
print('**********')
print('******')
print('*    *')
print('*    *')
print('******')
print('*')
print('**')
print('***')
print('****')
print((512-282)/47*48+5)
x = eval(input('Enter a number: '))
print('The square of this number is' , x*x)
x = eval(input('Enter a number'))
print(x*1, x*2, x*3, x*4, x*5)
a = eval(input('Enter the weight in kilograms: '))
print('The weight in pounds is' , a/2.2)